name: qdgs_exps
channels:
   - conda-forge
   - pytorch
   - nvidia
   - defaults
dependencies:
   - pip=21.0.1
   - numpy=1.20.3
   - numpy-base=1.20.3
   - pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
   - torchvision=0.10.1=py38_cu111
   - pip:
      - alive-progress==1.6.2 
      - bokeh==2.4.3
      - dask==2.20.0
      - distributed==2.30.1
      - einops
      - fire==0.4.0
      - git+https://github.com/openai/CLIP.git
      - kornia
      - matplotlib==3.4.2
      - omegaconf
      - pytorch-lightning
      - seaborn==0.11.1
      - opencv-python-headless
      - ribs